export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const FETCH_VIDEO = 'FETCH_VIDEO';
export const POST_COMMENT = 'POST_COMMENT';
export const POST_UPLOAD = 'POST_UPLOAD';
export const VERIFY_CODE_SUCCESSFUL = 'VERIFY_CODE_SUCCESSFUL';
export const VERIFY_CODE_FAIL = 'VERIFY_CODE_FAIL';
